runtime: go112

handlers:
  # Otherwise, find file in static directory
  - url: /public
    static_dir: public

  # All URLs are handled by the Go application script
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  KMS_KEYRING_KEY_NAME: "projects/condo3/locations/global/keyRings/condo3/cryptoKeys/app"
  MEMCACHED_SERVER: "memcached-17716.c1.asia-northeast1-1.gce.cloud.redislabs.com:17716"

  # encoded by BASE64
  KMS_DOORKEEPER_ACCESS_TOKEN: "CiQAT3DMmLlQwLNqtLr5ulPeMF8gRguotG1yqz3pJ3Sv0UDaelwSPgBmE7EAhRtSyMzg2wxT0kzwkZi5hhjzOPTnCXqEcvFYtJ1x5a3Yn1alWBJs+B+tcRAjxbuQ8FMvHbKh47mc"
  KMS_MEMCACHED_USERNAME: "CiQAT3DMmA1l96ra49zvBOxwTrZxZnqCJl3w0MZtgxkoEYo7saUSMgBmE7EA2GxK8i8oDwffxIvB2oDqiYRejPzbIDigD53lYwom0clobFk35kPEsVixh74f"
  KMS_MEMCACHED_PASSWORD: "CiQAT3DMmGoXOc2PsmBigNN2h9bjR5+4SiOsND55w+bmYzTNxNgSSgBmE7EAP6TdJrIdS8HXbGSVlfzyed7PwKbzBCSkWXj4xmK7n9q8zrEEg3PY7JHEkIlfuYyY0bNxgnAtr/PwgNT7aOdxv3wsACpq"

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 0
  max_concurrent_requests: 80
