version: 2.1

orbs:
  go-module: timakin/go-module@0.3.0

executors:
  golang:
    docker:
      # FIXME: google-cloud-sdk-datastore-emulator requires openjdk-8-jdk, but only openjdk-11-jdk is available on buster
      - image: circleci/golang:1.12-stretch
      - image: memcached:1.5-alpine
    working_directory: /home/circleci/app
    environment:
      TZ: Asia/Tokyo
      MEMCACHED_SERVER: "127.0.0.1:11211"

  node:
    docker:
      - image: circleci/node
    working_directory: /home/circleci/app

jobs:
  test:
    executor: golang

    steps:
      - &attach_workspace
        attach_workspace:
          at: /home/circleci/app
      - &restore_cache
        restore_cache:
          key: go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}

      - run: go get -u golang.org/x/lint/golint
      - run: make lint
      - run: make vet
      - run: "! gofmt -d . | grep '^'"

      - run: make test
      - run: make testrace

#   golint:
#     executor: golang
#
#     steps:
#       - *attach_workspace
#       - *restore_cache
#       - run: go get -u golang.org/x/lint/golint
#       - run: make lint
#
#   go-vet:
#     executor: golang
#
#     steps:
#       - *attach_workspace
#       - *restore_cache
#       - run: make vet
#
#   gofmt:
#     executor: golang
#
#     steps:
#       - *attach_workspace
#       - *restore_cache
#       - run: "! gofmt -d . | grep '^'"

  webpack:
    executor: node

    steps:
      - checkout
      - run: npm ci
      - run: NODE_ENV=production npm run build
      - persist_to_workspace:
          root: /home/circleci/app
          paths:
            - public/js/*
            - public/css/*

  deploy:
    docker:
      - image: google/cloud-sdk:alpine

    working_directory: /home/circleci/app

    steps:
      - checkout
      - *attach_workspace
      - run: gcloud --version
      - run: echo $BASE64_SERVICE_ACCOUNT_KEY | base64 -d > /tmp/service_account_key.json
      - run: gcloud auth activate-service-account --key-file /tmp/service_account_key.json
      - run: gcloud --project $APPENGINE_PROJECT_ID app deploy

workflows:
  build-and-deploy:
    jobs:
      - go-module/download:
          executor: golang
          persist-to-workspace: true

      - test:
          requires:
            - go-module/download

#       - golint:
#           requires:
#             - go-module/download
#
#       - go-vet:
#           requires:
#             - go-module/download
#
#       - gofmt:
#           requires:
#             - go-module/download

      - webpack

      - deploy:
          requires:
            - test
            # - golint
            # - go-vet
            # - gofmt
            - webpack
          filters:
            branches:
              only: master
