version: 2.1

orbs:
  codeclimate: sue445/codeclimate@volatile
  go-module:   timakin/go-module@0.3.0

executors:
  golang:
    docker:
      # FIXME: google-cloud-sdk-datastore-emulator requires openjdk-8-jdk, but only openjdk-11-jdk is available on buster
      - image: circleci/golang:1.12-stretch-node
      - image: memcached:1.5-alpine
    working_directory: /go/src/github.com/sue445/condo3
    environment:
      TZ: Asia/Tokyo
      MEMCACHED_SERVER: "127.0.0.1:11211"
      GO111MODULE: "on"

jobs:
  test:
    executor: golang

    environment:
      CC_TEST_REPORTER_ID: 62f4b81c3edd3cc6a6c2e2218dbdbf24e724f5c9244df2b3358e4405ff45727b
      TEST_ARGS: "-coverprofile c.out"

    steps:
      - &attach_workspace
        attach_workspace:
          at: /go/src/github.com/sue445/condo3
      - &restore_cache
        restore_cache:
          key: go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}

      - codeclimate/with-cc-test-reporter:
          steps:
            - run: make test
            - run: make testrace

  lint:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: go get -u golang.org/x/lint/golint
      - run: make lint
      - run: make vet
      - run: "! gofmt -d . | grep '^'"

  webpack:
    executor: golang

    steps:
      - checkout
      - run: npm ci
      - run: NODE_ENV=production npm run build
      - persist_to_workspace:
          root: /go/src/github.com/sue445/condo3
          paths:
            - public/js/*
            - public/css/*

  deploy:
    docker:
      - image: google/cloud-sdk:alpine

    working_directory: /go/src/github.com/sue445/condo3

    steps:
      - checkout
      - *attach_workspace
      - run: gcloud --version
      - run: echo $BASE64_SERVICE_ACCOUNT_KEY | base64 -d > /tmp/service_account_key.json
      - run: gcloud auth activate-service-account --key-file /tmp/service_account_key.json
      - run: gcloud --project $APPENGINE_PROJECT_ID app deploy

workflows:
  build-and-deploy:
    jobs:
      - go-module/download:
          executor: golang
          persist-to-workspace: true

      - test:
          requires:
            - go-module/download

      - lint:
          requires:
            - go-module/download

      - webpack

      - deploy:
          requires:
            - test
            - lint
            - webpack
          context: gcp_condo3
          filters:
            branches:
              only: master
